export const THEME = {
  light: {
    background: '#ffffff',
    foreground: '#09090b',
    card: '#ffffff',
    cardForeground: '#09090b',
    popover: '#ffffff',
    popoverForeground: '#09090b',
    primary: '#10b981',
    primaryForeground: '#ecfdf5',
    secondary: '#f4f4f5',
    secondaryForeground: '#18181b',
    muted: '#f5f5f5',
    mutedForeground: '#71717a',
    accent: '#f5f5f5',
    accentForeground: '#18181b',
    destructive: '#dc2626',
    destructiveForeground: '#fafafa',
    border: '#e4e4e7',
    input: '#e4e4e7',
    ring: '#a1a1aa',
    success: '#16a34a',
    successForeground: '#f0fdf4',
    warning: '#d97706',
    warningForeground: '#fffbeb',
    info: '#2563eb',
    infoForeground: '#eff6ff',
  },
  dark: {
    background: '#09090b',
    foreground: '#fafafa',
    card: '#18181b',
    cardForeground: '#fafafa',
    popover: '#18181b',
    popoverForeground: '#fafafa',
    primary: '#2dd4a8',
    primaryForeground: '#042f2e',
    secondary: '#27272a',
    secondaryForeground: '#fafafa',
    muted: '#27272a',
    mutedForeground: '#a1a1aa',
    accent: '#3f3f46',
    accentForeground: '#fafafa',
    destructive: '#f87171',
    destructiveForeground: '#ffffff',
    border: 'rgba(255, 255, 255, 0.1)',
    input: 'rgba(255, 255, 255, 0.15)',
    ring: '#71717a',
    success: '#22c55e',
    successForeground: '#052e16',
    warning: '#f59e0b',
    warningForeground: '#422006',
    info: '#3b82f6',
    infoForeground: '#eff6ff',
  },
} as const;

export const RNR_THEME = THEME;

export const NAV_THEME = {
  light: {
    background: THEME.light.background,
    foreground: THEME.light.foreground,
    card: THEME.light.card,
    cardForeground: THEME.light.cardForeground,
    primary: THEME.light.primary,
    primaryForeground: THEME.light.primaryForeground,
    secondary: THEME.light.secondary,
    secondaryForeground: THEME.light.secondaryForeground,
    muted: THEME.light.muted,
    mutedForeground: THEME.light.mutedForeground,
    accent: THEME.light.accent,
    accentForeground: THEME.light.accentForeground,
    destructive: THEME.light.destructive,
    destructiveForeground: THEME.light.destructiveForeground,
    border: THEME.light.border,
    input: THEME.light.input,
    ring: THEME.light.ring,
    success: THEME.light.success,
    successForeground: THEME.light.successForeground,
    warning: THEME.light.warning,
    warningForeground: THEME.light.warningForeground,
    info: THEME.light.info,
    infoForeground: THEME.light.infoForeground,
  },
  dark: {
    background: THEME.dark.background,
    foreground: THEME.dark.foreground,
    card: THEME.dark.card,
    cardForeground: THEME.dark.cardForeground,
    primary: THEME.dark.primary,
    primaryForeground: THEME.dark.primaryForeground,
    secondary: THEME.dark.secondary,
    secondaryForeground: THEME.dark.secondaryForeground,
    muted: THEME.dark.muted,
    mutedForeground: THEME.dark.mutedForeground,
    accent: THEME.dark.accent,
    accentForeground: THEME.dark.accentForeground,
    destructive: THEME.dark.destructive,
    destructiveForeground: THEME.dark.destructiveForeground,
    border: THEME.dark.border,
    input: THEME.dark.input,
    ring: THEME.dark.ring,
    success: THEME.dark.success,
    successForeground: THEME.dark.successForeground,
    warning: THEME.dark.warning,
    warningForeground: THEME.dark.warningForeground,
    info: THEME.dark.info,
    infoForeground: THEME.dark.infoForeground,
  },
} as const;
